---
driver:
  name: vagrant


provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: precise-server-cloudimg-amd64-vagrant-disk1
      box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
#  - name: centos-6.4

suites:
  - name: default
    run_list:
#      - recipe[thumbor::default]
      - recipe[minitest-handler]
      - recipe[thumbor_test]
    attributes:
